<?php

/**
 * hook login
 */
function cookie_redirect_user_login(&$edit, $account) {
  global $_domain;

  watchdog('info', "Form id = " . $_POST['form_id']);
  
  if (array_key_exists('form_id', $_POST) && $_POST['form_id'] != 'user_pass_reset') {
    // set the cookie to current time + 24h
    setcookie('cookieRedirect', 1, time() + 86400, '/', $_domain);

    // check if a redirect is needed
    cookie_redirect_do_redirect();
  }
}

/**
 * hook logout
 */
function cookie_redirect_user_logout($account) {
  // delete the cookie
  setcookie('cookieRedirect', '', time() - 3600);
}

/**
 * hook init
 */
function cookie_redirect_init() {
  // check if a redirect is needed
  cookie_redirect_do_redirect();
}

function cookie_redirect_do_redirect() {
  global $user;
  
  // check if the user is logged in 
  if ($user->uid) {
    // check if the query parameter "rd" is set
    $queryParameters = drupal_get_query_parameters();
    if (array_key_exists('rd', $queryParameters)) {
      // redirect to the target website
      drupal_goto($queryParameters['rd'], array('external' => TRUE));
    }
  }
}

/**
 * admin settings menu
 */
function cookie_redirect_menu() {
  $items['admin/config/system/cookieredirect'] = array(
    'title' => 'Cookie Redirect configure',
    'description' => 'Specify the redirect URL and other settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cookie_redirect_admin_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'cookie_redirect.admin.inc',
  );
 
  return $items;
}
